[snippets]
name1 = "/fake/file/path" # Inline comment
name2 = "/fake/file/path/2"

[snippets.groups]
snippetGroup = ['/fake/group/path', 
                '/fake/group/path2', 
                '/fake/group/path3']
snippetGroup2 = ['/fake/gro/path',
                '/fake/gro/path/2',
                '/fake/gro/path/3']

snippetGroup3 = ['/fake/gro/pa',
                '/fake/gro/pah/2',
                '/fke/gro/path/3']

snippetGroup4 = ['/fake', '/path', '/again']

# Non inline comment